name: scrumlab_flutter_share
description: A Flutter plugin for sharing images & text with other applications.
version: 2.0.2
homepage: https://github.com/scrum-lab/scrumlab-flutter-share

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4 #1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.scrumlab.scrumlabfluttershare
        pluginClass: ScrumlabFlutterSharePlugin
